### ISSUE TITLE
Release with ldapauth 4.0.1 and logger?

### ISSUE THREAD

**Issue by akdor1154** [Alexandre-io/verdaccio-ldap#10]
Hey,
Thanks for your work in maintaining this. 

With LdapAuth > v4, LdapAuth now accepts a parameter 'log' that takes a bunyan logger. You can happily pass in Verdaccio's logger here and get LdapAuth's logs showing up in Verdaccio's.

Aside from this, any chance for a release with the updated dependencies? :)

Jarrad

**Comment by Alexandre-io** [comment]
Hey! Fixed with version 1.2.0
