### ISSUE TITLE
v.1.4.0 doesn't work

### ISSUE THREAD

**Issue by z-eos** [Alexandre-io/verdaccio-ldap#22]
I've built docker with verdaccio-ldap: verdaccio/2.7.4 + verdaccio-ldap@1.4.0

as far as I can see from verdaccio trace, the very ldap auth is successfull, but the result is still „error: bad username/password, access denied“

looks like the very verdaccio miss interprets verdaccio-ldap results

[verdaccio-ldap.error.log](https://github.com/Alexandre-io/verdaccio-ldap/files/1728368/verdaccio-ldap.error.log)

**Comment by Alexandre-io** [comment]
Could you try with the latest version (2.0.0) ? thanks!
