### ISSUE TITLE
[Feat] STARTTLS

### ISSUE THREAD

**Issue by kopax** [Alexandre-io/verdaccio-ldap#34]
We are trying to solve #33 and instead of using `ldaps://` to use `ldap://`. 

But we need to have encryption, so we need to have it with `STARTTLS`.

We have tried to see if the current plugin was able to deal with `ldap://` and `STARTTLS` but it was not.

This feature request concern an improvement to allow starttls.

**Comment by Alexandre-io** [comment]
This feature must be implemented in `node-ldapauth-fork` (cf. https://github.com/vesse/node-ldapauth-fork/issues/59)
