### ISSUE TITLE
Verdaccio generates lots of authentication requests to LDAP

### ISSUE THREAD

**Issue by rankun203** [Alexandre-io/verdaccio-ldap#37]
and possibly crashes LDAP.

I'm currently investigating on an issue that causes our npm-registry stopped working.

On first sight, it's LDAP that stopped working, as you can see in [this issue](https://github.com/osixia/docker-openldap/issues/228), it failed with _too many open files_ error.

If we use `yarn add <package>`, then everything is fine, but if we use `npm install`, registry server is constantly requesting ldap server and finally at some point, ldap server crashes.

I had to restart ldap server twice to let npm install a package.

Possible reasons:

- Registry server logs have a lot of warnings

  ```
  warn --- basic authentication is deprecated, please use JWT instead
  ```

  I'm thinking that if jwt is used, registry server need only one request to ldap server while login the user with `npm adduser` (maybe).
- I have `cache: True` set in ldap settings (it was `False`, I'm testing with `True`), maybe it's not working.
- Our OpenLDAP server is too weak to handle that many requests(config issue).

**Comment by juanpicado** [comment]
Refers to https://github.com/verdaccio/verdaccio/issues/732

**Comment by rankun203** [comment]
@juanpicado I'm a little curious how jwt works in Verdaccio and its plugins? I thought it's perfect for distributed authentication. Also I noted Verdaccio is warning about not using jwt, so I guess Verdaccio may supports some feature about it.

**Comment by juanpicado** [comment]
@rankun203 we are working on normalizing the Token Authentication. https://github.com/verdaccio/verdaccio/issues/168#issuecomment-394149624

Remember this project never was documented and really really hard to maintain, nowadays is not a problem anymore, but some spots are still WIP, token is one of them. JWT will be soon the main feature to be implemented.

**Comment by kopax** [comment]
Hi @juanpicado , I am still looking forward to re-use ldap plugin when I'll get time to work on it.

I don't really get how #168 can help with the authentication spam the backend service. 

How will the JWT solve that ? What's the status? 

Also, what is the opinion of @Alexandre-io about it? How did you manage to use this plugin in real life we were only having LDAP not handling one request and failing the `npm install` command...

**Comment by juanpicado** [comment]
#168 won't solve that issue. It was just a comment about the current roadmap. Status is in backlog at the moment.

**Comment by Alexandre-io** [comment]
Can you give me your feedback with verdaccio 3.3.0 and verdaccio-ldap 2.3.0? thx

**Comment by kopax** [comment]
@Alexandre-io I saw that you didn't pick the node-cache version, why? Was the `cache` option already existing before?=/

**Comment by kopax** [comment]
Did anyone succeeded to activate the cache with latest version?
