### ISSUE TITLE
Fast login expiration

### ISSUE THREAD

**Issue by Eomm** [Alexandre-io/verdaccio-ldap#57]
Hi,
I'm using this plugin with verdaccio v3.11.6 and npm 6.4.1
We have ldap with 2FA enabled.

If I run these commands with `cache: false`:

```
> npm login --registry http://myverdaccio:4873 --scope=@mycompany

Username: manuel.spigolon
Password: <psw+OTP>
Email: (this IS public) asd@asd.aa
Logged in as manuel.spigolon to scope @mycompany on http://myverdaccio:4873/.

> cat `npm config get userconfig`
(token maskered)
//myverdaccio:4873/:_authToken="cutLAAAfbbb0XXmppppmeW1ACCCbtD0JYY1ZZZZLgAE="
@mycompany:registry=http://myverdaccio:4873/

> npm whoami --registry http://myverdaccio:4873

npm ERR! code ENEEDAUTH
npm ERR! need auth Your auth token is no longer valid. Please log in again.
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

if I set `cache: true`, `npm whoami --registry http://myverdaccio:4873` (and all the commands like publish and install) works for 5 minutes: the timing of the cache.

I saw that this configuration is pass to the module [ldapauth-fork](https://github.com/vesse/node-ldapauth-fork) but I was wondering why this token without cache expire immediately.

Could you help me to understand this behaviour? There are something that I have misconfig?
Thanks a lot

**Comment by kopax** [comment]
Hi, sorry if I am not replying to your question but I might if I can get going with it.

I am interested to work with ldap and verdaccio for a while and I'd like to know if you are able to work with it properly without the 2FA.

Did they fix the relogin issue between each request?

**Comment by Eomm** [comment]
> I'd like to know if you are able to work with it properly without the 2FA.

I didn't test it and right now I can't try since I changed company so I'm not using verdaccio.

> Did they fix the relogin issue between each request?

No, I created a [verdaccio plugin](https://github.com/Eomm/verdaccio-static-token) to introduce token as a workaround to login
